#Versions of services from Bundle. Don't update this file manually.
#Mon Jul 20 04:13:55 UTC 2026
bundle.product.name=YouTrack
previously-started-product-version=2026.2.16593
service.hub.previously-started-version=2026.2.52037
service.youtrack.previously-started-version=2026.2.16593
